name: FastAPI Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "1 0 * * 4"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      # - name: Initialize submodules
      #   run: git submodule update --init --recursive
      #     git config --global credential.helper store
      #     git config --global user.email "aryan19027@iiitd.ac.in"
      #     git config --global user.name "tanejaaryan"
      #     git config --global user.password "YOUR_PERSONAL_ACCESS_TOKEN"
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your requirements file
        working-directory: ./fast_backend

      # - name: Run FastAPI build script
      #   run: |
      #     uvicorn main:app --host 0.0.0.0
      #   working-directory: ./fast_backend

      - name: Start FastAPI server
        run: |
          uvicorn main:app --host 0.0.0.0 &
          sleep 3  # Wait for a few seconds to allow the server to start
        working-directory: ./fast_backend

      # Add more steps here if needed

      - name: Stop FastAPI server
        run: |
          pkill -f "uvicorn main:app"
        working-directory: ./fast_backend
