name: Frontend Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "1 0 * * 4"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Change directory to root
        run: cd ./frontend

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./frontend
        
#       - name: Building Node
#         run: npm run build --if-present
#         working-directory: ./frontend
        
#       - name: Running tests
#         run: npm test --if-present
#         working-directory: ./frontend
